# Generated by Django 4.1.7 on 2023-03-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrPokoju', models.IntegerField()),
                ('nazwa', models.CharField(max_length=30)),
                ('liczbaOsob', models.IntegerField()),
                ('dlaNiepelnosparwnych', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_przyjazdu', models.DateField()),
                ('data_wyjazdu', models.DateField()),
                ('gosc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezerwacja_apka.gosc')),
                ('pokoj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezerwacja_apka.pokoj')),
            ],
        ),
    ]
